# coding: utf-8


from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from ..serialization import deserialize_model

 
class Type(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    VLAN = "vlan"
    VETH = "veth"
    VCAN = "vcan"
    VXCAN = "vxcan"
    DUMMY = "dummy"
    IFB = "ifb"
    MACVLAN = "macvlan"
    MACVTAP = "macvtap"
    BRIDGE = "bridge"
    BOND = "bond"
    TEAM = "team"
    IPOIB = "ipoib"
    IP6TNL = "ip6tnl"
    IPIP = "ipip"
    SIT = "sit"
    VXLAN = "vxlan"
    GRE = "gre"
    GRETAP = "gretap"
    ERSPAN = "erspan"
    IP6GRE = "ip6gre"
    IP6GRETAP = "ip6gretap"
    IP6ERSPAN = "ip6erspan"
    VTI = "vti"
    NLMON = "nlmon"
    TEAM_SLAVE = "team_slave"
    BOND_SLAVE = "bond_slave"
    IPVLAN = "ipvlan"
    GENEVE = "geneve"
    BRIDGE_SLAVE = "bridge_slave"
    VRF = "vrf"
    MACSEC = "macsec"

    def __init__(self):  # noqa: E501
        """Type - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Type':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Type of this Type.  # noqa: E501
        :rtype: Type
        """
        return deserialize_model(dikt, cls)
